# Rebinding the prefix key
unbind M-m
set-option -g prefix M-m
bind M-m send-prefix

bind v split-window -h -c "#{pane_current_path}" "zsh"
bind s split-window -v -c "#{pane_current_path}" "zsh"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind w switch-client -T window-switch

bind -T window-switch k previous-window
bind -T window-switch l next-window 
bind -T window-switch Escape switch-client -T root
bind -T window-switch C-c switch-client -T root

set -g mouse on
setw -g mode-keys vi
set-option -g default-shell $SHELL
set-option -g automatic-rename on
