preload = /home/yardrat/Workbench/Imgs/Waifu/Lapwing_Darken_CLI.png
wallpaper = eDP-1,/home/yardrat/Workbench/Imgs/Waifu/Lapwing_Darken_CLI.png
wallpaper = HDMI-A-1,/home/yardrat/Workbench/Imgs/Waifu/Lapwing_Darken_CLI.png
