# Font
font_family Maple Mono NL NFMono CN
bold_font auto
font_size 16.0

# Cursor
cursor_shape beam
cursor_blink_interval 0.4

# Scrollback
scrollback_lines 1000
wheel_scroll_multiplier 3

# Window
initial_window_width 120c
initial_window_height 35c
window_padding_width 5

# Clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Behavior
confirm_os_window_close 0
enable_audio_bell no
allow_remote_control yes
shell_integration enabled


# Tabs and splits
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab

map ctrl+shift+enter launch --location=hsplit
map ctrl+shift+d launch --location=vsplit

map ctrl+shift+[ previous_tab
map ctrl+shift+] next_tab


# Mouse / copy behavior
copy_on_select yes
strip_trailing_spaces smart
mouse_hide_wait 3.0


# Colors
background_image /home/yardrat/Workbench/Imgs/Waifu/Lapwing_Darken.jpg
background_image_layout cscaled
background #263238
foreground #CAD9D9

color0  #000000
color1  #D4465D
color2  #A0C572
color3  #D4A858
color4  #6B8ED9
color5  #A67AC4
color6  #72B9D9
color7  #D9D9D9

color8  #455A63
color9  #D4465D
color10 #A0C572
color11 #D4A858
color12 #6B8ED9
color13 #A67AC4
color14 #72B9D9
color15 #CAD9D9

tab_bar_margin_width      20
tab_bar_margin_height     20 0
tab_bar_style             separator
tab_bar_min_tabs          2
tab_separator             ""
tab_title_template        "{fmt.fg._455A63}{fmt.bg.default}{fmt.fg._CAD9D9}{fmt.bg._455A63} {title.split()[0]} {fmt.fg._455A63}{fmt.bg.default} "
active_tab_title_template "{fmt.fg._6B8ED9}{fmt.bg.default}{fmt.fg._CAD9D9}{fmt.bg._6B8ED9} {title.split()[0]} {fmt.fg._6B8ED9}{fmt.bg.default} "
